export const cn = {
  // JSCC24
  abstract_book_url:
    "https://www.dropbox.com/scl/fi/jytt3lfcdhpuotmpwjw0s/abstract.pdf?rlkey=zmwgiaeblqw2a9vyhqc2qf4xv&dl=0",
  program_book_url:
    "https://www.dropbox.com/scl/fi/tqhd246w5oubbz4kny83u/program.pdf?rlkey=598c6ud1nkuwyvjuist2ikkai&dl=0",
  day0: "9月14日 (星期日)",
  day1: "9月15日 (星期一)",
  day2: "9月16日 (星期二)",
  day3: "9月17日 (星期三)",
  // msg1: "论文集可从以下链接获得; PDF文件的密码是abst75jscc。",
  venue: "长崎大学",
  venue_url: "static/全体図.pdf",
  awardvenue: "长崎大学",
  awardvenue_url: "static/全体図.pdf",
  banquetvenue: "新长崎酒店",
  banquetvenue_url: "https://www.newnaga.com/access/",
  hcvenue: "长崎大学",
  hcvenue_url: "static/全体図.pdf",
  luncheonvenue: "G-38教室",
  Layout: "布局图",
  Map: "地图",
  JSCCAS: "JSCC 第75次讨论会议",
  postervenue_url: "static/poster_layout.pdf",
  oralvenue_url: "static/講演会場図.pdf",
  // common
  hint1: "你可以通过演讲编号，标题，关键词，研究地点和演讲者姓名进行搜索,",
  hint2: "可以使用正则表达式,",
  hint3: "点击图片，打开PDF,",
  hint4: "该显示基于应用数据，显示的一些标题和作者可能与摘要不同,",
  hint5:
    "按你感兴趣的讲座号码，在下表中会出现一个蓝色的勾，请用这个来帮助你安排你的出席",
  usingjs: "注意:这个搜索功能使用JavaScript,",
  "Morning sessions": "上午的会议",
  "Afternoon sessions": "下午的会议",
  "Poster sessions": "海报",
  "Oral sessions": "口头报告",
  "Award lectures": "获奖讲座",
  Banquet: "宴席",
  "JSCC general meeting": "JSCC大会",
  Supporters: "赞助商",
  "General Information": "信息",
  "Overall schedule": "时间表",
  SEARCH: "搜索",
  "JSCC Research Encouragement Award": "JSCC研究鼓励奖",
  "JSCC International Award for Creative Work": "JSCC国际创意作品奖",
  "JSCC Award": "JSCC奖",
  "JSCC International Award": "JSCC国际奖",
  "JSCC Award for Creative Work": "JSCC学术奖",
  "JSCC International Award": "JSCC国际奖",
  "JSCC Contribution Award": "JSCC贡献奖",
  "Homecoming Day": "JSCC 返校日",
  "Luncheon seminars": "午餐研讨会",
  Symposia: "专题讨论会",
  msg2: "如果您想参加招待会，请用下面的链接预订座位。(用户名和密码与本网站相同。)",
  Announcements: "公告",
  "Seat reservation for the banquet": "招待会的座位预订",
  "Award lectures": "得奖演讲",
  "(In preparation.)": "(正在准备中)",
  "Abstract book": "摘要书",
  "Program book": "辩论会方案集",
  "(lightweight)": "(轻量级版本)",
  "Opening Remark": "开场词",
  "Closing Remark": "闭幕词",
  Explanation: "说明",
};
