export const ja={
    "hint1": "発表番号、題目、キーワード、研究場所、発表者名にて検索が可能です.",
    "hint2": "正規表現が使えます.",
    "hint3": "画像クリックでPDFが開きます.",
    "hint4": "表示は申込データに基づいており、表示のタイトルおよび著者の一部が要旨とは異なる場合があります.",
    "hint5": "興味のある講演番号を押すと、下の表に青い印が付きます. 聴講スケジュールを決めるのにご活用下さい.",
    "centerzone2": "九州大学伊都キャンパス センター２号館",
    "mainhall": "福岡国際会議場 メインホール",
    "Fukuoka International Congress Center": "福岡国際会議場",
    "hotelokura": "ホテルオークラ福岡",
    "Hotel Okura Fukuoka": "ホテルオークラ福岡",
    "usingjs": "注意: この検索機能は JavaScript を使用しています.",
    "sept26": "9月26日 (月)",
    "sept27": "9月27日 (火)",
    "sept28": "9月28日 (水)",
    "Morning sessions": "午前の部",
    "Afternoon sessions": "午後の部",
    "Poster sessions": "ポスター",
    "Oral sessions": "口頭発表",
    "Award lectures": "受賞講演",
    "Banquet": "懇親会",
    "JSCC general meeting": "錯体化学会総会",
    "Supporters": "協賛企業",
    "General Information": "ご案内",
    "Overall schedule": "日程",
    "SEARCH": "検索",
    "JSCC Research Encouragement Award": "錯体化学会　研究奨励賞",
    "JSCC International Award for Creative Work": "錯体化学会　国際奨励賞",
    "JSCC Award": "錯体化学会　学会賞",
    "JSCC International Award": "錯体化学会　国際賞",
    "JSCC Award for Creative Work": "錯体化学会　学術賞",
    "JSCC International Award": "錯体化学会　国際賞",
    "JSCC Contribution Award": "錯体化学会　貢献賞",
    "Symposia": "シンポジウム",
    "msg1": "予稿集は以下のリンクより入手できます。PDFファイルのパスワードは abst72jscc です。",
    "msg2": "懇親会にご参加される方は、以下のリンクより座席をご予約ねがいます。ユーザ名・パスワードはこのサイトと同じです。ひさびさに顔をあわせるご友人とお連れあわせいただき、心ゆくまでご歓談いただければと思います。",
    "Announcements": "お知らせ",
    "Seat reservation for the banquet": "懇親会の座席予約",
    "Award lectures": "受賞講演",
    "(In preparation.)": "(準備中)",
    "Abstract book": "講演要旨集",
    "Program book": "討論会プログラム集",
    "(lightweight)": "(軽量版)",
    "JSCCAS": "錯体化学会 第72回討論会"
}
